#!/bin/bash

project="$1"
sha="$2"
site="$3"
env="$4"
dashboard_url="$5"
site_url="$6"

token="$(composer config --global github-oauth.github.com)"

# Exit immediately on errors
set -e

body="Created new staging environment for ${site}#${env}. Here are some useful links:\n\n"
body+="[Pantheon Dashboard](${dashboard_url})\n"
if [ -n "$site_url" ] ; then
	body+="[WordPress Admin](${site_url}/wp/wp-admin)\n\n"

	key_pages=$(cat ../../key_pages.json)
	page_labels=(`echo $key_pages | jq '.[].label'`)
	page_urls=(`echo $key_pages | jq '.[].url'`)
	for ((i=0;i<${#page_urls[@]};++i)); do
	    body+="[${page_labels[i]//\"}](${site_url}/${page_urls[i]//\"})\n"
	done
fi

if [ -n "$token" ] ; then
  curl -d '{ "body": "'"$body"'" }' -X POST https://api.github.com/repos/$project/commits/$sha/comments?access_token=$token
fi

printf "$body\n"